// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Address$ReView = require("./Elements/Address.bs.js");
var Article$ReView = require("./Elements/Article.bs.js");
var HTMLElement$ReView = require("./HTMLElement.bs.js");

var Address = HTMLElement$ReView.WithChild(Address$ReView);

var Article = HTMLElement$ReView.WithChild(Article$ReView);

exports.Address = Address;
exports.Article = Article;
/* Address Not a pure module */
