// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var DOM$ReView = require("../DOM.bs.js");

function WithoutChild(El) {
  var tag = El.tag;
  var make = function (base, props) {
    return Curry._2(DOM$ReView.DomCore.Host.make, base, {
                constructor: tag,
                attributes: props.attributes,
                children: undefined
              });
  };
  return {
          tag: tag,
          make: make
        };
}

function WithChild(El) {
  var tag = El.tag;
  var make = function (base, props) {
    return Curry._2(DOM$ReView.DomCore.Host.make, base, {
                constructor: tag,
                attributes: props.attributes,
                children: props.children
              });
  };
  return {
          tag: tag,
          make: make
        };
}

exports.WithoutChild = WithoutChild;
exports.WithChild = WithChild;
/* DOM-ReView Not a pure module */
