// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Exception$ReView = require("../Exception.bs.js");
var RenderContext$ReView = require("../RenderContext.bs.js");

function use(supplier) {
  if (RenderContext$ReView.isActive(/* () */0)) {
    var match = RenderContext$ReView.getContext(/* () */0);
    var slot = match.slot;
    var node = match.node;
    var current = slot.contents;
    var state = node.getState(current);
    if (state !== undefined) {
      slot.contents = current + 1 | 0;
      return Caml_option.valFromOption(state);
    } else {
      var value = Curry._1(supplier, /* () */0);
      node.setState(current, value);
      slot.contents = current + 1 | 0;
      return value;
    }
  } else {
    throw Exception$ReView.IllegalRenderContextAccess;
  }
}

exports.use = use;
/* RenderContext-ReView Not a pure module */
