// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Exception$ReView = require("../Exception.bs.js");
var RenderContext$ReView = require("../RenderContext.bs.js");

function use(supplier) {
  if (RenderContext$ReView.isActive(/* () */0)) {
    var match = RenderContext$ReView.getContext(/* () */0);
    var slot = match.slot;
    var node = match.node;
    var current = slot.contents;
    var state = node.getState(current);
    if (state !== undefined) {
      var match$1 = state;
      if (match$1.tag === /* Constant */1) {
        slot.contents = current + 1 | 0;
        return match$1[0];
      } else {
        throw Exception$ReView.IllegalSlotAccess;
      }
    } else {
      var value = Curry._1(supplier, /* () */0);
      node.setState(current, /* Constant */Block.__(1, [value]));
      slot.contents = current + 1 | 0;
      return value;
    }
  } else {
    throw Exception$ReView.IllegalRenderContextAccess;
  }
}

exports.use = use;
/* RenderContext-ReView Not a pure module */
