// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Exception$ReView = require("../Exception.bs.js");
var RenderContext$ReView = require("../RenderContext.bs.js");

function use(initialValue) {
  if (RenderContext$ReView.isActive(/* () */0)) {
    var match = RenderContext$ReView.getContext(/* () */0);
    var slot = match.slot;
    var node = match.node;
    var current = slot.contents;
    var state = node.getState(current);
    if (state !== undefined) {
      slot.contents = current + 1 | 0;
      return state;
    } else {
      var value = {
        contents: initialValue
      };
      node.setState(current, value);
      slot.contents = current + 1 | 0;
      return value;
    }
  } else {
    throw Exception$ReView.IllegalRenderContextAccess;
  }
}

exports.use = use;
/* RenderContext-ReView Not a pure module */
