// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Component$ReView = require("../Component.bs.js");
var Reconciler$ReView = require("../Reconciler.bs.js");
var RenderContext$ReView = require("../RenderContext.bs.js");

var make = Component$ReView.make("Fragment", (function (children) {
        var match = RenderContext$ReView.getContext(/* () */0);
        var root = match.root;
        var parent = match.parent;
        List.iteri((function ($$int, i) {
                if (i !== undefined) {
                  return Reconciler$ReView.render(Caml_option.valFromOption(i), parent, $$int, Caml_option.some(root));
                } else {
                  return /* () */0;
                }
              }), children);
        return ;
      }));

exports.make = make;
/* make Not a pure module */
