// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Component$ReView = require("../Component.bs.js");
var Reconciler$ReView = require("../Reconciler.bs.js");
var RenderContext$ReView = require("../RenderContext.bs.js");

var make = Component$ReView.make("Fragment", (function (param) {
        var match = RenderContext$ReView.getContext(/* () */0);
        var root = match.root;
        var node = match.node;
        List.iteri((function (id, child) {
                if (child !== undefined) {
                  return Reconciler$ReView.render(Caml_option.valFromOption(child), node, id, Caml_option.some(root));
                } else {
                  var match = root.getNode(id);
                  if (match !== undefined) {
                    return Reconciler$ReView.unmount(Caml_option.valFromOption(match), root, id);
                  } else {
                    return /* () */0;
                  }
                }
              }), param.children);
        return ;
      }));

exports.make = make;
/* make Not a pure module */
