// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Node$ReView = require("./Node.bs.js");

function make(name, render) {
  var component = {
    name: name,
    render: render
  };
  return (function (props) {
      return Caml_option.some(Node$ReView.make(component, props));
    });
}

exports.make = make;
/* Node-ReView Not a pure module */
