// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Node$ReView = require("./Node.bs.js");

function make(name, render) {
  var component = {
    name: name,
    render: render
  };
  return (function (props) {
      var node = Node$ReView.make(component, props);
      return /* Some */Block.__(0, [node]);
    });
}

exports.make = make;
/* Node-ReView Not a pure module */
