// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Engine$ReView = require("./Engine.bs.js");
var DomJs = require("./bindings/dom.js");

function createInstance(prim, prim$1) {
  return DomJs.createInstance(prim, prim$1);
}

function appendChild(prim, prim$1, prim$2) {
  DomJs.appendChild(prim, prim$1, prim$2);
  return /* () */0;
}

function removeChild(prim, prim$1, prim$2) {
  DomJs.removeChild(prim, prim$1, prim$2);
  return /* () */0;
}

function commitUpdate(prim, prim$1, prim$2, prim$3) {
  DomJs.removeChild(prim, prim$1, prim$2, prim$3);
  return /* () */0;
}

var Reconciler = {
  createInstance: createInstance,
  appendChild: appendChild,
  removeChild: removeChild,
  commitUpdate: commitUpdate
};

var DomCore = Engine$ReView.Make(Reconciler);

var render = DomCore.Core.render;

var useCallback = DomCore.useCallback;

var useConstant = DomCore.useConstant;

var useContext = DomCore.useContext;

var useEffect = DomCore.useEffect;

var useForceUpdate = DomCore.useForceUpdate;

var useIdentifier = DomCore.useIdentifier;

var useLayoutEffect = DomCore.useLayoutEffect;

var useMemo = DomCore.useMemo;

var useMutable = DomCore.useMutable;

var useReducer = DomCore.useReducer;

var useReference = DomCore.useReference;

var useState = DomCore.useState;

var Context = /* alias */0;

var Fragment = /* alias */0;

var ErrorBoundary = /* alias */0;

var Basic = /* alias */0;

var MemoBasic = /* alias */0;

var Component = /* alias */0;

var Memo = /* alias */0;

exports.Reconciler = Reconciler;
exports.DomCore = DomCore;
exports.render = render;
exports.useCallback = useCallback;
exports.useConstant = useConstant;
exports.useContext = useContext;
exports.useEffect = useEffect;
exports.useForceUpdate = useForceUpdate;
exports.useIdentifier = useIdentifier;
exports.useLayoutEffect = useLayoutEffect;
exports.useMemo = useMemo;
exports.useMutable = useMutable;
exports.useReducer = useReducer;
exports.useReference = useReference;
exports.useState = useState;
exports.Context = Context;
exports.Fragment = Fragment;
exports.ErrorBoundary = ErrorBoundary;
exports.Basic = Basic;
exports.MemoBasic = MemoBasic;
exports.Component = Component;
exports.Memo = Memo;
/* DomCore Not a pure module */
