// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var IllegalRenderContextAccess = Caml_exceptions.create("Exception-ReView.IllegalRenderContextAccess");

var IllegalSlotAccess = Caml_exceptions.create("Exception-ReView.IllegalSlotAccess");

exports.IllegalRenderContextAccess = IllegalRenderContextAccess;
exports.IllegalSlotAccess = IllegalSlotAccess;
/* No side effect */
