// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var MissingBasicComponentConstructor = Caml_exceptions.create("Exceptions-ReView.MissingBasicComponentConstructor");

var MissingComponentConstructor = Caml_exceptions.create("Exceptions-ReView.MissingComponentConstructor");

var MissingMemoComponentConstructor = Caml_exceptions.create("Exceptions-ReView.MissingMemoComponentConstructor");

var MissingMemoBasicComponentConstructor = Caml_exceptions.create("Exceptions-ReView.MissingMemoBasicComponentConstructor");

var OutOfContextHookCall = Caml_exceptions.create("Exceptions-ReView.OutOfContextHookCall");

var IncompatibleHook = Caml_exceptions.create("Exceptions-ReView.IncompatibleHook");

var MissingContext = Caml_exceptions.create("Exceptions-ReView.MissingContext");

var DesyncContextValue = Caml_exceptions.create("Exceptions-ReView.DesyncContextValue");

var UnboundContextInstance = Caml_exceptions.create("Exceptions-ReView.UnboundContextInstance");

var InvalidHostConstructor = Caml_exceptions.create("Exceptions-ReView.InvalidHostConstructor");

var MissingWorkInProgressRoot = Caml_exceptions.create("Exceptions-ReView.MissingWorkInProgressRoot");

var MissingCurrentRoot = Caml_exceptions.create("Exceptions-ReView.MissingCurrentRoot");

exports.MissingBasicComponentConstructor = MissingBasicComponentConstructor;
exports.MissingComponentConstructor = MissingComponentConstructor;
exports.MissingMemoComponentConstructor = MissingMemoComponentConstructor;
exports.MissingMemoBasicComponentConstructor = MissingMemoBasicComponentConstructor;
exports.OutOfContextHookCall = OutOfContextHookCall;
exports.IncompatibleHook = IncompatibleHook;
exports.MissingContext = MissingContext;
exports.DesyncContextValue = DesyncContextValue;
exports.UnboundContextInstance = UnboundContextInstance;
exports.InvalidHostConstructor = InvalidHostConstructor;
exports.MissingWorkInProgressRoot = MissingWorkInProgressRoot;
exports.MissingCurrentRoot = MissingCurrentRoot;
/* No side effect */
