// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var MissingBasicComponentConstructor = Caml_exceptions.create("Exceptions-ReView.MissingBasicComponentConstructor");

var OutOfContextHookCall = Caml_exceptions.create("Exceptions-ReView.OutOfContextHookCall");

var IncompatibleHook = Caml_exceptions.create("Exceptions-ReView.IncompatibleHook");

var MissingContext = Caml_exceptions.create("Exceptions-ReView.MissingContext");

var DesyncContextValue = Caml_exceptions.create("Exceptions-ReView.DesyncContextValue");

var UnboundContextInstance = Caml_exceptions.create("Exceptions-ReView.UnboundContextInstance");

var InvalidHostConstructor = Caml_exceptions.create("Exceptions-ReView.InvalidHostConstructor");

exports.MissingBasicComponentConstructor = MissingBasicComponentConstructor;
exports.OutOfContextHookCall = OutOfContextHookCall;
exports.IncompatibleHook = IncompatibleHook;
exports.MissingContext = MissingContext;
exports.DesyncContextValue = DesyncContextValue;
exports.UnboundContextInstance = UnboundContextInstance;
exports.InvalidHostConstructor = InvalidHostConstructor;
/* No side effect */
