exception MissingBasicComponentConstructor;
exception OutOfContextHookCall;
exception IncompatibleHook;
exception MissingContext;
exception DesyncContextValue;
exception UnboundContextInstance;
exception InvalidHostConstructor;
