// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function let_(value, mapper) {
  if (value !== undefined) {
    return Curry._1(mapper, Caml_option.valFromOption(value));
  }
  
}

var $$Option = {
  let_: let_
};

function let_$1(value, mapper) {
  if (value !== undefined) {
    Curry._1(mapper, Caml_option.valFromOption(value));
    return ;
  }
  
}

var OptionUnit = {
  let_: let_$1
};

function let_$2(param, mapper) {
  var value = param[0];
  if (value !== undefined) {
    return Curry._1(mapper, Caml_option.valFromOption(value));
  }
  throw param[1];
}

var OptionOrError = {
  let_: let_$2
};

exports.$$Option = $$Option;
exports.OptionUnit = OptionUnit;
exports.OptionOrError = OptionOrError;
/* No side effect */
