// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ModuleResolverJs = require("./bindings/ModuleResolver.js");

function getModule(prim) {
  return ModuleResolverJs.getModule(prim);
}

function setModule(prim, prim$1) {
  ModuleResolverJs.setModule(prim, prim$1);
  return /* () */0;
}

exports.getModule = getModule;
exports.setModule = setModule;
/* ./bindings/ModuleResolver.js Not a pure module */
