// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var NodeJs = require("./bindings/Node.js");

function make(prim, prim$1) {
  return new NodeJs.Node(prim, prim$1);
}

function toEquatable(prim) {
  return NodeJs.toEquatable(prim);
}

exports.make = make;
exports.toEquatable = toEquatable;
/* ./bindings/Node.js Not a pure module */
