// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var IdentityJs = require("./bindings/identity.js");
var NativeMapJs = require("./bindings/native-map.js");
var NativeSetJs = require("./bindings/native-set.js");
var NativeArrayJs = require("./bindings/native-array.js");

function $$return(prim) {
  return IdentityJs(prim);
}

function convert(prim) {
  return IdentityJs(prim);
}

function make(prim) {
  return NativeArrayJs.makeArray();
}

function set(prim, prim$1, prim$2) {
  NativeArrayJs.arraySet(prim, prim$1, prim$2);
  return /* () */0;
}

function get(prim, prim$1) {
  return NativeArrayJs.arrayGet(prim, prim$1);
}

function forEach(prim, prim$1) {
  NativeArrayJs.arrayForEach(prim, prim$1);
  return /* () */0;
}

var $$Array = {
  make: make,
  set: set,
  get: get,
  forEach: forEach
};

function make$1(prim) {
  return NativeMapJs.makeMap();
}

function set$1(prim, prim$1, prim$2) {
  NativeMapJs.mapSet(prim, prim$1, prim$2);
  return /* () */0;
}

function get$1(prim, prim$1) {
  return NativeMapJs.mapGet(prim, prim$1);
}

function has(prim, prim$1) {
  return NativeMapJs.mapHas(prim, prim$1);
}

var $$Map = {
  make: make$1,
  set: set$1,
  get: get$1,
  has: has
};

function make$2(prim) {
  return NativeSetJs.makeSet();
}

function add(prim, prim$1) {
  NativeSetJs.setAdd(prim, prim$1);
  return /* () */0;
}

function has$1(prim, prim$1) {
  return NativeSetJs.setHas(prim, prim$1);
}

function forEach$1(prim, prim$1) {
  NativeSetJs.setForEach(prim, prim$1);
  return /* () */0;
}

var $$Set = {
  make: make$2,
  add: add,
  has: has$1,
  forEach: forEach$1
};

exports.$$return = $$return;
exports.convert = convert;
exports.$$Array = $$Array;
exports.$$Map = $$Map;
exports.$$Set = $$Set;
/* ./bindings/identity.js Not a pure module */
