// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Reconciler$ReView = require("./Reconciler.bs.js");

function call(node, root) {
  if (node !== undefined) {
    return Reconciler$ReView.render(Caml_option.valFromOption(node), root, undefined, undefined);
  } else {
    return /* () */0;
  }
}

exports.call = call;
/* Reconciler-ReView Not a pure module */
