// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var RenderContextJs = require("./bindings/RenderContext.js");

function setContext(prim) {
  RenderContextJs.setContext(prim);
  return /* () */0;
}

function getContext(prim) {
  return RenderContextJs.getContext();
}

function popContext(prim) {
  RenderContextJs.popContext();
  return /* () */0;
}

function isActive(prim) {
  return RenderContextJs.isActive();
}

exports.setContext = setContext;
exports.getContext = getContext;
exports.popContext = popContext;
exports.isActive = isActive;
/* ./bindings/RenderContext.js Not a pure module */
