// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Reconciler$ReView = require("./Reconciler.bs.js");

function call(node, root) {
  return Reconciler$ReView.renderResult(node, root, 0, root);
}

exports.call = call;
/* Reconciler-ReView Not a pure module */
