// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Fiber = { };

var Work = { };

var Hook = { };

exports.Fiber = Fiber;
exports.Work = Work;
exports.Hook = Hook;
/* No side effect */
