// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ScheduleAsyncJs = require("./bindings/scheduleAsync.js");

function scheduleAsync(prim) {
  ScheduleAsyncJs.scheduleAsync(prim);
  return /* () */0;
}

exports.scheduleAsync = scheduleAsync;
/* ./bindings/scheduleAsync.js Not a pure module */
